---
- name: Copy files into controller node
  when: inventory_hostname in groups['controller']
  loop:
    - ca.pem
    - ca-key.pem
    - kubernetes-key.pem
    - kubernetes.pem
    - service-account-key.pem
    - service-account.pem
  ansible.builtin.copy:
    mode: u=rw,g=r,o=r
    src: "{{ item }}"
    dest: /home/ubuntu

- name: Copy ca files into worker node
  when: inventory_hostname in groups['worker']
  ansible.builtin.copy:
    mode: u=rw,g=r,o=r
    src: ca.pem
    dest: /home/ubuntu

- name: Copy ca files into worker node
  when: inventory_hostname in groups['worker']
  loop:
    - 0
    - 1
    - 2
  ansible.builtin.copy:
    mode: u=rw,g=r,o=r
    src: "worker-{{ item }}-key.pem"
    dest: /home/ubuntu

- name: Copy ca files into worker node
  when: inventory_hostname in groups['worker']
  loop:
    - 0
    - 1
    - 2
  ansible.builtin.copy:
    mode: u=rw,g=r,o=r
    src: "worker-{{ item }}-key.pem"
    dest: /home/ubuntu
