---
- name: Install kubectl
  ansible.builtin.get_url:
    url: https://dl.k8s.io/release/v{{ kubectl.version }}/bin/{{ os.name }}/{{ os.arch }}/kubectl
    dest: /usr/local/bin/kubectl
    mode: a+x

- name: Install cfssl
  ansible.builtin.get_url:
    url: https://github.com/cloudflare/cfssl/releases/download/v{{ cfssl.version }}/cfssl_{{ cfssl.version }}_{{ os.name }}_{{ os.arch }}
    dest: /usr/local/bin/cfssl
    mode: a+x

- name: Install cfssljson
  ansible.builtin.get_url:
    url: https://github.com/cloudflare/cfssl/releases/download/v{{ cfssl.version }}/cfssljson_{{ cfssl.version }}_{{ os.name }}_{{ os.arch }}
    dest: /usr/local/bin/cfssljson
    mode: a+x
