---
- name: Generate a kubeconfig file suitable for authenticating as the admin user
  when: inventory_hostname == "localhost"
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      kubectl config set-cluster kubernetes-the-hard-way \
        --certificate-authority=ca.pem \
        --embed-certs=true \
        --server=https://{{ kubernetes_public_address }}:443

      kubectl config set-credentials admin \
        --client-certificate=admin.pem \
        --client-key=admin-key.pem

      kubectl config set-context kubernetes-the-hard-way \
        --cluster=kubernetes-the-hard-way \
        --user=admin

      kubectl config use-context kubernetes-the-hard-way
    executable: /bin/bash
  changed_when: true
