---
- name: Generate encryption key and render yml file
  when: inventory_hostname == "localhost"
  block:
    - name: Generate encryption key
      ansible.builtin.shell:
        cmd: |
          set -o pipefail
          head -c 32 /dev/urandom | base64
      register: encryption_key_output
      changed_when: true
    - name: Set encryption key as a variable
      ansible.builtin.set_fact:
        encryption_key: "{{ encryption_key_output.stdout }}"
    - name: Generate encryption config file
      ansible.builtin.template:
        src: "encryption-config.yaml.j2"
        dest: "{{ playbook_dir }}/encryption-config.yaml"
        mode: preserve
- name: Copy the encryption-config.yaml file to each controller instance
  when: inventory_hostname in groups['controller']
  ansible.builtin.copy:
    mode: u=rwx,g=r,o=r
    src: encryption-config.yaml
    dest: /home/ubuntu
