# This roles install prerequisite client tools in host machine
#
# - name: Install client tools
#   become: true
#   hosts: localhost
#   roles:
#     - client-tools

- name: Generate certificates and copy it to the nodes
  become: true
  hosts:
    - localhost
    - controller
    - worker
  roles:
    - certificate-authority
