# This roles install prerequisite client tools in host machine
#
# - name: Install client tools
#   become: true
#   hosts: localhost
#   roles:
#     - client-tools

- name: Generate certificates and copy it to the nodes
  become: true
  hosts:
    - localhost
    - controller
    - worker
  roles:
    - certificate-authority

- name: Generate kube-config files and copy it to the nodes
  become: true
  hosts:
    - localhost
    - controller
    - worker
  roles:
    - kubernetes-config-files

- name: Generate data-encryption config files and copy it to the nodes
  become: true
  hosts:
    - localhost
    - controller
  roles:
    - kubernetes-config-files
